name: Github Actions Input Demo

run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  workflow_call:

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: casa-vega/resuable-workflows
          path: reuse
      - name: Print the input name to STDOUT
        run: echo The username is ${{ inputs.username }}
        shell: bash
      - name: where am I
        run: ls -al
      - name: where am I
        run: ls -al reuse/
      - name: where am I
        run: ls -al reuse/.github
      - name: path
        run: pwd
      - name: Execute script
        run: bash ${{ github.action_path }}/test.sh
        shell: bash
